wandb:
  _target_: lightning.fabric.loggers.TensorBoardLogger
  root_dir: "${hydra:runtime.output_dir}"
  name: "logs"

# To use W&B instead, uncomment below and comment out above:
# wandb:
#   _target_: lightning.fabric.loggers.CSVLogger
#   root_dir: "${hydra:runtime.output_dir}"
#   name: "csv_logs"
