# @package _global_

seed: 42
deterministic: true

defaults:
  - _self_
  - data: default
  - model: default
  - trainer: default
  - logger: tensorboard
  - experiment: null
  - hparams_search: null
  - local: default
